# Generated by Django 5.0.3 on 2024-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'medicine_category_table',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date_of_manufacture', models.DateField(auto_now_add=True)),
                ('expiry', models.CharField(max_length=100)),
                ('power_in_mg', models.IntegerField()),
                ('manufactured_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'medicine_table',
            },
        ),
    ]
