# Generated by Django 5.0.3 on 2024-03-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_check'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table=None,
        ),
    ]
